name: Build Docker Container and push as Package

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Build and push
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: image-name
          registry: ghcr.io
          githubOrg: override-org # optional
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
